Style/Documentation:
  Description: "Document classes and non-namespace modules."
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/GuardClause:
  Enabled: false

  Layout/EmptyMethod:
    Enabled: false

Style/UnlessParentheses:
  Enabled: false